### ISSUE TITLE
배경색과 글자색이 비슷하여 가독성이 떨어짐

### ISSUE THREAD

**Issue by sebuls** [KiwiFlavoredApollo/phpBB-Korean-Language-Pack#1]
https://forum.fractalcoffee.duckdns.org/
들어가 봤습니다. 
배경색과 글자색이 비슷하여 눈이 좀 피곤하군요. 
저만 그런지도 모릅니다.

**Comment by KiwiFlavoredApollo** [comment]
>  배경색과 글자색이 비슷하여 눈이 좀 피곤하군요.

안녕하세요. 어두운 테마가 이런 맹점이 있었군요ㅠㅠ 그나마 제일 마음에 들었던 것이긴한데, 다른 테마가 있으면 바꿔봐야겠습니다. 현재 사용하고 있는 테마는 [Black 테마](https://www.phpbb.com/customise/db/style/black)입니다.

**Comment by sebuls** [comment]
제 글에 너무 부담 갖지 않으셔도 됩니다.
어떻게 하더라도 모든 사람을 만족시킬 수는 없겠지요 ;)
모든 사람을 만족시키려한다면 삶이 힘들어지겠지요?

2024년 4월 6일 (토) 09:35, KiwiFlavoredApollo ***@***.***>님이 작성:

**Comment by KiwiFlavoredApollo** [comment]
말씀 감사합니다! 그래도 이번 기회에 좀 더 이쁜 스타일(테마)이 없는지 둘러보게 되었습니다.
