### ISSUE TITLE
Translation bug?

### ISSUE THREAD

**Issue by sebuls** [KiwiFlavoredApollo/phpBB-Korean-Language-Pack#2]
https://forum.fractalcoffee.duckdns.org/ucp.php?mode=register

길이는 CHARACTERS_XY에서 CHARACTERS_XY 사이여야 합니다.
라고 나옵니다.
CHARACTERS_XY 대신에 숫자가 들어가야 될 듯.

**Comment by KiwiFlavoredApollo** [comment]
감사합니다. 8d627c2 에서 수정했습니다. `CHARACTERS_XY`가 누락되어 있었네요.

**Comment by sebuls** [comment]
Good.
